package topcoder.srm648;
import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class AB
{
    public String createString(int N, int K)
    {
        int maxK = (N / 2) * ((N + 1) / 2);

        if(K > maxK){
            return "";
        }

        int digit = N / 2;

        int numberOfAs = ((N + 1) / 2);

        int numberOfBs = digit;

        int numWholes = K / digit;

        int remainder = K % digit;

        int zeroes = numberOfAs - numWholes;

        if(remainder != 0){
            zeroes--;
        }

        StringBuilder result = new StringBuilder();

        for(int i = 0; i < numWholes; i++){
            result.append('A');
        }

        for(int i = numberOfBs; i > 0; i--){
            if(remainder == i){
                result.append('A');
            }
            result.append('B');
        }

        for(int i = 0; i < zeroes; i++){
            result.append('A');
        }


        return result.toString();
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, boolean hasAnswer, String p2) {
        System.out.print("Test " + testNum + ": [" + p0 + "," + p1);
        System.out.println("]");
        AB obj;
        String answer;
        obj = new AB();
        long startTime = System.currentTimeMillis();
        answer = obj.createString(p0, p1);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + "\"" + p2 + "\"");
        }
        System.out.println("Your answer:");
        System.out.println("\t" + "\"" + answer + "\"");
        if (hasAnswer) {
            res = answer.equals(p2);
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }
    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int p0;
        int p1;
        String p2;

        // ----- test 0 -----
        p0 = 3;
        p1 = 2;
        p2 = "AAB";
        all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = 2;
        p1 = 0;
        p2 = "BA";
        all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = 5;
        p1 = 8;
        p2 = "";
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = 10;
        p1 = 12;
        p2 = "AABBBABBAA";
        all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
        // ------------------


        // ----- test 4 -----
        p0 = 10;
        p1 = 25;
        p2 = "AAAAABBBBB";
        all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
        // ------------------


        // ----- test 4 -----
        p0 = 11;
        p1 = 25;
        p2 = "AAAAABBBBBA";
        all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 6 -----
        p0 = 15;
        p1 = 23;
        p2 = "AAABBBBBABBAAAA";
        all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
        // ------------------


        // ----- test 6 -----
        p0 = 15;
        p1 = 56;
        p2 = "AAAAAAAABBBBBBB";
        all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
        // ------------------



        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!