package topcoder.srm556;

import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class LeftRightDigitsGame2 {
    public String minNumber(String digits, String lowerBound) {
        Set<StringBuilder> mySet = new HashSet<StringBuilder>();
        for (int i = 0; i < digits.length(); i++) {
            Set<StringBuilder> myNewSet = new HashSet<StringBuilder>();
            if (mySet.isEmpty()) {
                myNewSet.add(new StringBuilder(digits.charAt(i) + ""));
            } else {
                for (StringBuilder myStringBuilder : mySet) {
                    myNewSet.add(new StringBuilder(digits.charAt(i) + myStringBuilder.toString()));
                    myNewSet.add(myStringBuilder.append(digits.charAt(i)));
                }
            }
            mySet = myNewSet;
        }
        List<String> myStrings = new ArrayList<String>();
        for (StringBuilder myStringBuilder : mySet) {
            myStrings.add(myStringBuilder.toString());
        }
        Collections.sort(myStrings);
        for(String myString : myStrings){
            if(myString.compareTo(lowerBound) >= 0){
                return myString;
            }
        }
        return "";
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, String p0, String p1, boolean hasAnswer, String p2) {
        System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "\"" + p1 + "\"");
        System.out.println("]");
        LeftRightDigitsGame2 obj;
        String answer;
        obj = new LeftRightDigitsGame2();
        long startTime = System.currentTimeMillis();
        answer = obj.minNumber(p0,
                               p1);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + "\"" + p2 + "\"");
        }
        System.out.println("Your answer:");
        System.out.println("\t" + "\"" + answer + "\"");
        if (hasAnswer) {
            res = answer.equals(p2);
        }
        if (! res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        String p0;
        String p1;
        String p2;

        // ----- test 0 -----
        p0 = "565";
        p1 = "556";
        p2 = "556";
        all_right = KawigiEdit_RunTest(0,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = "565";
        p1 = "566";
        p2 = "655";
        all_right = KawigiEdit_RunTest(1,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = "565";
        p1 = "656";
        p2 = "";
        all_right = KawigiEdit_RunTest(2,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = "9876543210";
        p1 = "5565565565";
        p2 = "5678943210";
        all_right = KawigiEdit_RunTest(3,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = "8016352";
        p1 = "1000000";
        p2 = "1086352";
        all_right = KawigiEdit_RunTest(4,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = "80163528016352801635280163528016352";
        p1 = "1000000";
        p2 = "1086352";
        all_right = KawigiEdit_RunTest(4,
                                       p0,
                                       p1,
                                       true,
                                       p2) && all_right;
        // ------------------


        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!